### PR TITLE
feat(Taiga #1415): Create Irish Grid Datatype

### PR DESCRIPTION
**Pull request by OwenGalvia**
# Create Irish Grid Reference Datatype

  - [ ] Bugfix (non-breaking change which fixes an issue)
  - [x] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Description of Change  

HED want to be able to input a Grid Reference or Northings and Eastings for the Irish grid and have Arches understand these.

### It must be able to:

    Allow users to input Irish Grid Values as part of the location data
    Place points on the map at the correct co-ordinate based on the grid reference
    Include Irish Grid Values in the report pages for resources

## Related Issues
[irish grid reference bugged](#1401 )

## Related Tickets
[first attempt](https://github.com/flaxandteal/coral-arches/pull/25)

[second attempt](https://github.com/flaxandteal/coral-arches/pull/42)
Checklist

TODO

    Unit tests pass locally with my changes
    I have added tests that prove my fix is effective or that my feature works
    I have provided screenshots / video of feature working (if it's a visual change)
    I have added necessary documentation (if appropriate)

Further comments:   
Early attempts were just for rendering wsg84 co-ordinates as Irish Grid Northing and Eastings on the map widget. I also stored that value as a string at one stage.

This is not what HED want. What they want is closer to Historic Englands [bng-point datatype](https://github.com/HistoricEngland/arches-bngpoint/tree/master) which has a widget that can create a grid reference from a geospatial point or vice versa.  

There are multiple Irish grids:
[TM65](https://epsg.io/29902) proj4.defs("EPSG:29902","+proj=tmerc +lat_0=53.5 +lon_0=-8 +k=1.000035 +x_0=200000 +y_0=250000 +a=6377340.189 +rf=299.3249646 +towgs84=482.5,-130.6,564.6,-1.042,-0.214,-0.631,8.15 +units=m +no_defs +type=crs");
[TM75](https://epsg.io/19972) proj4.defs("EPSG:19972","+proj=tmerc +lat_0=53.5 +lon_0=-8 +k=1.000035 +x_0=200000 +y_0=250000");
[ITM](https://epsg.io/9922) proj4.defs("EPSG:9922","+proj=tmerc +lat_0=53.5 +lon_0=-8 +k=0.99982 +x_0=600000 +y_0=750000 +ellps=GRS80 +units=m +vunits=m +no_defs +type=crs");

I believe (but should confirm) that it's TM75 that HED want to use. 

The steps to create this, following Historic England's example, will be:

    Create an Irish Grid Data Type
    Create functions to sync with geojson-feature-collection nodes
    Create Widget that allows users to input Grid Reference.

### CODE REVIEW

**Comment by OwenGalvia** [comment]
Troubleshoot
component not found error when trying to render card

I know the issue is not in the datatype python file since I tried putting a typo when getting the espg19972point widget. 
```python
# coral/datatypes/espg19972.py
espg19972point = Widget.objects.get(name="espg19972poin")

details = {
    "datatype": "espg19972centrepoint",
    "iconclass": "fa fa-location-arrow",
    "modulename": "espg19972centrepoint.py",
    "classname": "ESPG19972CentreDataType",
    "defaultwidget": espg19972point,
    "defaultconfig": None,
    "configcomponent": None,
    "configname": None,
    "isgeometric": False,
    "issearchable": False,
}
```
Doing this throws an error when registering / updating the datatype:
```
  File "/web_root/ENV/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
arches.app.models.models.Widget.DoesNotExist: Widget matching query does not exist.
```

Changing the component in the widget JSON to one that doesn't exist does not flag an error when registering / updating the widget. This could be where the issue is
```json
{
  "widgetid": "60328bdb-bac3-410b-bcee-6c05d7689b29",
  "name": "espg19972point",
  "component": "views/components/widgets/unexistingespg",
  "defaultconfig": {
    "placeholder": "Enter the centre point map reference of the resource."
  },
  "helptext": null,
  "datatype": "espg19972centrepoint"
}
```
I tried rebuilding webpack using 
`make webpack` this would load most templates and then error because docx-preview wasn't found. 
I wonder if the new template is meant to be loaded after this error takes place.

template not found

**Comment by OwenGalvia** [comment]
Even with the ability to render the card in the graph designer there are ongoing problems.

image

It does not render in the resource manager and states it is an Unknown component

**Comment by OwenGalvia** [comment]
Currently the Irish grid reference appears on the edit page as expected but not on the report page. 

location data group card shows the grid reference on edit page

report page does not show the grid reference

**Comment by OwenGalvia** [comment]
Currently when we make a point on the map it is converted to an Irish Grid Reference and saves it as the correct tile.
image
Despite it appearing on the cards endpoint and the resource page it does not appear on the report page.

image

**Review by taylorn01 — APPROVED** [review]

**Pull request merged**
