### PR TITLE
fix(Flag for Enforcement Workflow): Save even if bad recent resources found, e.g. from before a reset [#1712]

### PR DESCRIPTION
**Pull request by philtweir**
### What does this PR do?

Prevents an error being thrown if a resource in the local cache is no longer available (for example, due to a reset).

### How to review?

This is trickier - it was originally seen after a DB reset but it should be sufficient to test by deleting the resource after doing the workflow.

### Who can review?

@taylorn01 to confirm the fix. @hristiyanadeliyska or Jana to test on dev & UAT.

### CODE REVIEW

**Comment by philtweir** [comment]
Yep - it seemed strange, but the backtrace was showing that `init` calls `validateRecentlyOpened` and that is based on local storage, so will come back with resources even if it is the first workflow opened after a reset (with no resource chosen). The `loading(false)` call will never bit hit. Unless I am missing something, there is nothing different for the with/without existing workflow/resource paths there.

That said, I would have thought this would cause the issue when starting the workflow, not saving - but my memory was that this was the only backtrace visible, so maybe I am mixing up with where Hrisi said she couldn't open a workflow.

**Comment by taylorn01** [comment]
Yeah I think there's a couple things wrong. I've disabled the recently opened feature for now because the revisions workflows will store the origin resource id instead of the revision id to re-open.

**Comment by philtweir** [comment]
OK - should this one should be gtg, or do you reckon there's more to do to resolve the opening issue?

**Comment by taylorn01** [comment]
I've just updated there now, we've definitely fixed issues but I'm not 100% if we've fixed the intended issue. Struggling to replicate the bug, what do you think?

**Comment by philtweir** [comment]
I think we can merge this to begin with - @hristiyanadeliyska and Jana might have difficulty reproducing it regardless, but maybe Owen can if he hasn't done a cache clear on the current site?

**Comment by hristiyanadeliyska** [comment]
Flag for enforcement works fine for me now

**Pull request merged**
