### PR TITLE
Wip/feature/improved licence cover letter

### PR DESCRIPTION
**Pull request by OwenGalvia**
Made this as a separate branch to push now that there is an improved layout for the original cover letter. 
This is a split from wip/feature/cover-letter-changable-templates

### CODE REVIEW

**Review by taylorn01 — CHANGES_REQUESTED** [review]
Needs version 0.5.2 and diff needs fixed against the latest develop to remove "Adding cover letter to summary step" code

**Comment by OwenGalvia** [comment]
> Needs version 0.5.2 and diff needs fixed against the latest develop to remove "Adding cover letter to summary step" code

Did this yesterday and re-requested review.

**Comment by OwenGalvia** [comment]
Appears I've accidentally pushed commits to here which were meant for the changeable cover-letter workflow. I will try to amend or make the changeable cover letter ready for develop

**Comment by OwenGalvia** [comment]
> Appears I've accidentally pushed commits to here which were meant for the changeable cover-letter workflow. I will try to amend or make the changeable cover letter ready for develop

Fixed. It's now usable when changing. Not all fields have fields next to them but I believe this is ready to push what we have so far

**Review by taylorn01 — APPROVED** [review]
lgtm

**Pull request merged**
