### PR TITLE
Wip/bug/fixing small issues with develop

### PR DESCRIPTION
**Pull request by taylorn01**

### CODE REVIEW

**Review by OwenGalvia — APPROVED** [review]
Will need to either fix the location type cardinality/500 issue or make this a townlands field and prefill the type.

**Comment by OwenGalvia** [comment]
Changed location description back to a default card so that it works with many

**Comment by OwenGalvia** [comment]
@taylorn01 I Changed location description back to a default card so that it works with many. Have checked it locally and it works fine. Thought I'd be able to request a review from you for that change. Should have opened a new branch for that change but I'm happy to merge this if you are

**Review by OwenGalvia — APPROVED** [review]

**Comment by taylorn01** [comment]
Perfect that's much better than just setting it back to 1 the way I had it. In this case it's fine since it's just a generic branch for bugs that weren't recorded on Taiga for example

**Review by taylorn01 — COMMENTED** [review]
Looks good to me

**Pull request merged**
